steps:
  # Build APK with Gradle Image
- name: "gcr.io/cloud-builders/docker"
  args: ["run", "--volume", "/workspace:/workspace", "--rm", "gcr.io/fullstackgcp/gradle", "/bin/bash", "-c", "'cd /workspace && ./gradlew clean assembleDebug'"]
  # Push the APK Output to our GCS Bucket
- name: "gcr.io/cloud-builders/gsutil"
  args: ['cp', 'app/build/outputs/apk/debug/app-debug.apk', 'gs://fullstackgcp-apk-builds/app-debug-$SHORT_SHA.apk']
timeout: 1200s
