steps:
  # Set a persistent volume according to https://cloud.google.com/cloud-build/docs/build-config (search for volumes)
- name: 'ubuntu'
  volumes:
  - name: 'vol'
    path: '/persistent_volume'
  args: ['cp', '-a', '.', '/persistent_volume']
  # Build APK with Gradle Image from mounted /persistent_volume
- name: "gcr.io/cloud-builders/docker"
  volumes:
  - name: 'vol'
    path: '/persistent_volume'
  args: ["run", "-v", "/vol:/home/app", "--rm", "gcr.io/fullstackgcp/gradle", "/bin/bash", "-c", "ls -la"]
  # Push the APK Output to our GCS Bucket
- name: "gcr.io/cloud-builders/gsutil"
  volumes:
  - name: 'vol'
    path: '/persistent_volume'
  args: ['cp', '/persistent_volume/app/build/outputs/apk/debug/app-debug.apk', 'gs://fullstackgcp-apk-builds/app-debug-$SHORT_SHA.apk']
timeout: 1200s
