steps:
  # Build APK with Gradle Build
# - name: "gcr.io/cloud-builders/gradle"
#   args: ["build"]
- name: 'gcr.io/$PROJECT_ID/android:28'
  args: ["./gradlew", "assembleDebug"]
  # Push the APK Output to our GCS Bucket
- name: "gcr.io/cloud-builders/gsutil"
  args: ['cp', 'app/build/outputs/apk/debug/app-debug.apk', 'gs://timtech4u-apk-builds/app-debug.apk']
timeout: 1200s
