steps:
  # Build APK with Gradle Build
- name: "gcr.io/cloud-builders/gradle:latest"
  args: ["build"]
  # Push the APK Output to our GCS Bucket
- name: "gcr.io/cloud-builders/gsutil"
  args: ['cp', 'app/build/outputs/apk/debug/app-debug.apk', 'gs://timtech4u-apk-builds/app-debug.apk']
timeout: 1200s
